# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dekode/v1/types.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dekode/v1/types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64\x65kode/v1/types.proto\x12\tdekode.v1\"\xfb\x01\n\tSymbolRef\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x16\n\x0equalified_name\x18\x03 \x01(\t\x12\x0c\n\x04kind\x18\x04 \x01(\t\x12\x12\n\nvisibility\x18\x05 \x01(\t\x12\x11\n\tfile_path\x18\x06 \x01(\t\x12\x12\n\nstart_byte\x18\x07 \x01(\r\x12\x10\n\x08\x65nd_byte\x18\x08 \x01(\r\x12\x11\n\tsignature\x18\t \x01(\t\x12\x18\n\x0b\x64oc_comment\x18\n \x01(\tH\x00\x88\x01\x01\x12\x16\n\tparent_id\x18\x0b \x01(\tH\x01\x88\x01\x01\x42\x0e\n\x0c_doc_commentB\x0c\n\n_parent_id\"A\n\x0b\x43\x61llEdgeRef\x12\x11\n\tcaller_id\x18\x01 \x01(\t\x12\x11\n\tcallee_id\x18\x02 \x01(\t\x12\x0c\n\x04kind\x18\x03 \x01(\t\"Q\n\rDependencyRef\x12\x0f\n\x07package\x18\x01 \x01(\t\x12\x13\n\x0bversion_req\x18\x02 \x01(\t\x12\x1a\n\x12used_by_symbol_ids\x18\x03 \x03(\t\"\xa2\x01\n\x0bTypeInfoRef\x12\x11\n\tsymbol_id\x18\x01 \x01(\t\x12 \n\x06params\x18\x02 \x03(\x0b\x32\x10.dekode.v1.Param\x12\x18\n\x0breturn_type\x18\x03 \x01(\tH\x00\x88\x01\x01\x12 \n\x06\x66ields\x18\x04 \x03(\x0b\x32\x10.dekode.v1.Field\x12\x12\n\nimplements\x18\x05 \x03(\tB\x0e\n\x0c_return_type\"\'\n\x05Param\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08type_str\x18\x02 \x01(\t\"\'\n\x05\x46ield\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08type_str\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dekode.v1.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYMBOLREF']._serialized_start=37
  _globals['_SYMBOLREF']._serialized_end=288
  _globals['_CALLEDGEREF']._serialized_start=290
  _globals['_CALLEDGEREF']._serialized_end=355
  _globals['_DEPENDENCYREF']._serialized_start=357
  _globals['_DEPENDENCYREF']._serialized_end=438
  _globals['_TYPEINFOREF']._serialized_start=441
  _globals['_TYPEINFOREF']._serialized_end=603
  _globals['_PARAM']._serialized_start=605
  _globals['_PARAM']._serialized_end=644
  _globals['_FIELD']._serialized_start=646
  _globals['_FIELD']._serialized_end=685
# @@protoc_insertion_point(module_scope)
